/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/file/{type}/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene un archivo de descarga masiva
         *     GET: file/json/2024/01
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Es el tipo de archivo a descargar */
                    type: components["schemas"]["TipoArchivo"];
                    /**
                     * @description Año del archivo
                     * @example 2020
                     */
                    year: number;
                    /** @description Mes del archivo */
                    month: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MensajeResultadoDeOperacionesModelo"];
                        "application/json": components["schemas"]["MensajeResultadoDeOperacionesModelo"];
                        "text/json": components["schemas"]["MensajeResultadoDeOperacionesModelo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene una lista de archivos de descargas masivas */
        get: {
            parameters: {
                query?: {
                    /** @description Año del archivo */
                    year?: number;
                    /** @description Mes del archivo */
                    month?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilePkgRecord"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record/{ocid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene una lista de RecordPackage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Es el identificador del record Default value : <b>ocds-xqjsxa-16024362</b> */
                    ocid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/searchNog/{nog}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtine el último release, por identificador NOG (Número de operación de Guatecompras)
         *     Ejemplo: 16024362
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description NOG (Número de operación de Guatecompras) */
                    nog: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HeaderRelease"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Búsqueda y lista de releases por ciertos criterios, recorrido secuencial (método Search alter) para explorar más de 10,000 resultados
         * @description **Tabla de parámetros:**
         *
         *     Parámetro | Descripción | Ejemplo
         *     --------- | ----------- | ----------
         *     anio | Año de la publicacion | 2021
         *     mes | Mes de la publicación | 2 dígitos => 10 (Octubre)
         *     dia | Día de la publicación | 2 dígitos => 25
         *     tipo_entidad | Tipo de entidad | dígitos
         *     sub_tipo_entidad | Sub tipo de entidad | dígitos
         *     entidad | Entidad compradora | dígitos
         *     unidad_compradora | Unidad compradora | dígitos
         *     modalidad_compradora | Modalidad de compra | dígitos
         *     sub_modalidad_compradora | Sub modalidad de compra | dígitos
         *     estatus_concurso | Estado de concurso | dígitos
         *
         *     **Nota:** parámetro de tiempo obligatorio (Año ó Mes ó Día)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Obtiene un número de página específica del los Releases o Entregas */
                    pagina?: number;
                    /** @description Ordena los releases por la fecha publicación */
                    ordenamiento?: components["schemas"]["orderDatePublishNOG"];
                    /** @description Año de la publicacion */
                    Anio?: number;
                    /** @description Mes de la publicación */
                    Mes?: number;
                    /** @description Día de la publicación */
                    Dia?: number;
                    /** @description Tipo de entidad */
                    Tipo_entidad?: number;
                    /** @description Sub tipo de entidad */
                    Sub_tipo_entidad?: number;
                    /** @description Entidad compradora */
                    Entidad?: number;
                    /** @description Unidad compradora */
                    Unidad_compradora?: number;
                    /** @description Modalidad de compra */
                    Modalidad_compradora?: number;
                    /** @description Sub modalidad de compra */
                    Sub_modalidad_compradora?: number;
                    /** @description Estado de concurso */
                    Estatus_concurso?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HeaderRelease"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene un release por el identificador
         *     Ejemplo de un identificador de release:  GT-NOG-17047528-T637979723532777654
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identificador de release. Ejemplo: GT-NOG-17047528-T637979723532777654 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdditionalContactPoints: {
            name?: string | null;
            email?: string | null;
            telephone?: string | null;
            availableLanguage?: string[] | null;
        };
        Address: {
            streetAddress?: string | null;
            locality?: string | null;
            region?: string | null;
            countryName?: string | null;
        };
        attributes: {
            name?: string | null;
            id?: string | null;
            value?: string | null;
        };
        Awards: {
            id?: string | null;
            title?: string | null;
            status?: string | null;
            statusDetails?: string | null;
            date?: string | null;
            value?: components["schemas"]["Value"];
            suppliers?: components["schemas"]["Estructura_Id_Nombre"][] | null;
        };
        Bids: {
            details?: components["schemas"]["Details"][] | null;
        };
        ContactPoint: {
            name?: string | null;
            email?: string | null;
            telephone?: string | null;
            faxNumber?: string | null;
            url?: string | null;
        };
        Contracts: {
            id?: string | null;
            awardID?: string | null;
            title?: string | null;
            contractNumber?: string | null;
            status?: string | null;
            statusDetails?: string | null;
            dateSigned?: string | null;
            period?: components["schemas"]["TenderPeriod"];
            value?: components["schemas"]["Value"];
            documents?: components["schemas"]["Documents"][] | null;
            implementation?: components["schemas"]["Implementation"];
        };
        DataSegmentation: {
            id?: string | null;
            criteria?: string[] | null;
        };
        Details: {
            id?: string | null;
            date?: string | null;
            status?: string | null;
            value?: components["schemas"]["Value"];
            tenderers?: components["schemas"]["Estructura_Id_Nombre"][] | null;
        };
        DetailsTender: {
            level?: components["schemas"]["Estructura_Id_Descrip"];
            legalEntityTypeDetail?: components["schemas"]["Estructura_Id_Descrip"];
            entityType?: components["schemas"]["Estructura_Id_Descrip"];
            type?: components["schemas"]["Estructura_Id_Descrip"];
        };
        Documents: {
            id?: string | null;
            documentType?: string | null;
            title?: string | null;
            url?: string | null;
            format?: string | null;
            language?: string | null;
            description?: string | null;
            datePublished?: string | null;
            documentTypeDetails?: string | null;
        };
        Estructura_Id_Descrip: {
            id?: string | null;
            description?: string | null;
        };
        Estructura_Id_Nombre: {
            name?: string | null;
            id?: string | null;
        };
        Estructura_Nombre: {
            name?: string | null;
        };
        Estructura_Nombre_compuesto: {
            scheme?: string | null;
            uid?: string | null;
            name?: string | null;
            uri?: string | null;
        };
        FilePkgRecord: {
            result?: components["schemas"]["ResultFilePkgRecord"][] | null;
        };
        FileRecord: {
            csv?: string | null;
            xlsx?: string | null;
            json?: string | null;
            sha?: string | null;
        };
        HeaderRelease: {
            uri?: string | null;
            version?: string | null;
            extensions?: string[] | null;
            publishedDate?: string | null;
            license?: string | null;
            publisher?: components["schemas"]["Estructura_Nombre_compuesto"];
            releases?: components["schemas"]["Releases"][] | null;
            publicationPolicy?: string | null;
            links?: components["schemas"]["Pagination"];
        };
        Identifier: {
            id?: string | null;
            scheme?: string | null;
        };
        Implementation: {
            transactions?: components["schemas"]["Transaction"][] | null;
        };
        Items: {
            id?: string | null;
            description?: string | null;
            classification?: components["schemas"]["Identifier"];
            /** Format: double */
            quantity?: number;
            unit?: components["schemas"]["Estructura_Nombre"];
            attributes?: components["schemas"]["attributes"][] | null;
        };
        MensajeResultadoDeOperacionesModelo: {
            status?: components["schemas"]["statusMessage"];
            operacionRealizadaConExito?: boolean;
            mensajeOperacion?: string | null;
        };
        /** @enum {string} */
        orderDatePublishNOG: "Asc" | "Desc";
        Pagination: {
            next?: string | null;
            prev?: string | null;
        };
        Parties: {
            name?: string | null;
            id?: string | null;
            identifier?: components["schemas"]["Identifier"];
            address?: components["schemas"]["Address"];
            contactPoint?: components["schemas"]["ContactPoint"];
            roles?: string[] | null;
            additionalContactPoints?: components["schemas"]["AdditionalContactPoints"][] | null;
            memberOf?: components["schemas"]["Estructura_Id_Nombre"][] | null;
            details?: components["schemas"]["DetailsTender"];
        };
        Releases: {
            id?: string | null;
            ocid?: string | null;
            date?: string | null;
            publishedDate?: string | null;
            language?: string | null;
            tag?: string[] | null;
            initiationType?: string | null;
            parties?: components["schemas"]["Parties"][] | null;
            buyer?: components["schemas"]["Estructura_Id_Nombre"];
            bids?: components["schemas"]["Bids"];
            tender?: components["schemas"]["Tender"];
            awards?: components["schemas"]["Awards"][] | null;
            contracts?: components["schemas"]["Contracts"][] | null;
            sources?: components["schemas"]["Sources"][] | null;
            dataSegmentation?: components["schemas"]["DataSegmentation"];
        };
        ResultFilePkgRecord: {
            id?: string | null;
            files?: components["schemas"]["FileRecord"];
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            monthName?: string | null;
            source?: string | null;
            timestamp?: string | null;
        };
        Sources: {
            name?: string | null;
            id?: string | null;
            url?: string | null;
        };
        /** @enum {string} */
        statusMessage: "Success" | "Notcontent" | "Error" | "Warning";
        Tender: {
            id?: string | null;
            title?: string | null;
            status?: string | null;
            statusDetails?: string | null;
            datePublished?: string | null;
            procuringEntity?: components["schemas"]["Estructura_Id_Nombre"];
            items?: components["schemas"]["Items"][] | null;
            procurementMethod?: string | null;
            procurementMethodDetails?: string | null;
            mainProcurementCategory?: string | null;
            additionalProcurementCategories?: string[] | null;
            submissionMethod?: string[] | null;
            submissionMethodDetails?: string | null;
            tenderPeriod?: components["schemas"]["TenderPeriod"];
            /** Format: int32 */
            numberOfTenderers?: number;
            tenderers?: components["schemas"]["Estructura_Id_Nombre"][] | null;
            documents?: components["schemas"]["Documents"][] | null;
        };
        TenderPeriod: {
            startDate?: string | null;
            endDate?: string | null;
        };
        /** @enum {string} */
        TipoArchivo: "json" | "xlsx" | "csv";
        Transaction: {
            id?: string | null;
            value?: components["schemas"]["Value"];
            payer?: components["schemas"]["Estructura_Id_Nombre"];
            payee?: components["schemas"]["Estructura_Id_Nombre"];
        };
        Value: {
            /** Format: double */
            amount?: number;
            currency?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
