// ===========================================
// GuateVigila SDK - Mock Data
// ===========================================

import type {
  Alert,
  AlertDetail,
  Entity,
  Supplier,
  GlobalStats,
  EntityListItem,
  SupplierListItem,
} from './types'

// Global Stats
export const mockGlobalStats: GlobalStats = {
  processesAnalyzed: 276599,
  totalAmount: 31700000000,
  currency: 'GTQ',
  periodStart: 2020,
  periodEnd: 2024,
  activeAlerts: 847,
}

// Alerts
export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    entityId: 'entity-001',
    entityName: 'Ministerio de Comunicaciones, Infraestructura y Vivienda',
    riskLevel: 'high',
    signalType: 'Proveedor único recurrente',
    signalIcon: 'warning',
    year: '2024',
    contractCount: 14,
    totalAmount: 142800000,
    currency: 'GTQ',
  },
  {
    id: 'alert-002',
    entityId: 'entity-002',
    entityName: 'Municipalidad de Guatemala',
    riskLevel: 'medium',
    signalType: 'Fraccionamiento de gasto',
    signalIcon: 'timeline',
    year: '2023',
    contractCount: 8,
    totalAmount: 24500000,
    currency: 'GTQ',
  },
  {
    id: 'alert-003',
    entityId: 'entity-003',
    entityName: 'Ministerio de Salud Pública y Asistencia Social',
    riskLevel: 'high',
    signalType: 'Plazos de licitación reducidos',
    signalIcon: 'priority_high',
    year: '2024',
    contractCount: 3,
    totalAmount: 89200000,
    currency: 'GTQ',
  },
  {
    id: 'alert-004',
    entityId: 'entity-004',
    entityName: 'Instituto Guatemalteco de Seguridad Social',
    riskLevel: 'medium',
    signalType: 'Concentración en grupo empresarial',
    signalIcon: 'group',
    year: '2023–2024',
    contractCount: 52,
    totalAmount: 312000000,
    currency: 'GTQ',
  },
]

// Alert Details
export const mockAlertDetails: Record<string, AlertDetail> = {
  'alert-004': {
    id: 'alert-004',
    entityId: 'entity-004',
    entityName: 'Instituto Guatemalteco de Seguridad Social',
    description:
      'Anomalía detectada en el proceso de adquisición de suministros médicos para la región metropolitana. Patrones de concentración de mercado identificados.',
    riskScore: 94,
    riskLevel: 'critical',
    signals: [
      {
        id: 'signal-001',
        type: 'provider-concentration',
        title: 'Dominio del 85% del mercado',
        description: 'Concentración de Proveedor',
        icon: 'warning',
        metrics: [
          { label: 'vs. Promedio sectorial', value: '+62%' },
          { label: 'Contratos vigentes', value: '12' },
        ],
      },
      {
        id: 'signal-002',
        type: 'price-variation',
        title: 'Sobrecosto estimado del 24%',
        description: 'Variación de Precios',
        icon: 'monitoring',
        metrics: [
          { label: 'vs. Histórico entidad', value: '+15%' },
          { label: 'Eventos afectados', value: '4' },
        ],
      },
      {
        id: 'signal-003',
        type: 'bidding-time',
        title: 'Ventana de oferta reducida (48h)',
        description: 'Tiempo de Licitación',
        icon: 'timer_off',
        metrics: [
          { label: 'vs. Plazo legal recomendado', value: '-70%' },
          { label: 'Proceso', value: 'NOG 18239401' },
        ],
      },
    ],
    involvedSupplier: {
      id: 'supplier-002',
      name: 'Suministros Médicos del Norte, S.A.',
      nit: '8392104-5',
      totalAwarded: 14250900,
      year: 2024,
    },
    draftInvestigation: `La auditoría de datos en GuateVigila ha detectado una anomalía crítica en el Instituto Guatemalteco de Seguridad Social (IGSS). Durante el último trimestre, el 85% de las adjudicaciones para equipo quirúrgico han sido asignadas a un único proveedor, superando por un margen del 62% el promedio de concentración de mercado del sector salud. Los documentos analizados revelan ventanas de licitación inusualmente cortas, de apenas 48 horas, lo que sugiere un posible direccionamiento de las bases. Esta práctica coincide con un incremento del 24% en los costos unitarios comparados con el mercado regional, representando un potencial perjuicio económico de millones de quetzales para la seguridad social guatemalteca.`,
    networkMapUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQnO3mDXmtk2fnkxJBRYiQ58hXEEvkzg1jW7D9nVAoSI0EK4fBdcb18nFsHlHV2e3M1bt4_QejyeuxwskqkNqAzrj8gZ_CnZqS7xKIgQWPcwEXwJURGkU1U3mWX75gfnAOeA05ElzVjhXRORk2i4XAzB9yqQZGzOcHgMQootURUkzvJTfYyucxyRzWg7Ymzmmkg0QkD17Zw_88UwLry-FgcaS_dz8MAbce3aV0Xspi-HyRh5Aj4vWPN2GAPS2eyM6bfqy-gXCUUXY',
  },
}

// Entities
export const mockEntities: Record<string, Entity> = {
  'entity-001': {
    id: 'entity-001',
    name: 'Ministerio de Comunicaciones, Infraestructura y Vivienda',
    shortName: 'MICIVI',
    totalContracts: 1482,
    totalAmount: 4200000000,
    currency: 'GTQ',
    directPurchasePercentage: 62.4,
    activeAlerts: 14,
    yearlyData: [
      { year: 2020, amount: 420000000, label: 'Q420M' },
      { year: 2021, amount: 890000000, label: 'Q890M' },
      { year: 2022, amount: 1200000000, label: 'Q1.2B' },
      { year: 2023, amount: 1800000000, label: 'Q1.8B' },
      { year: 2024, amount: 4200000000, label: 'Q4.2B' },
    ],
    topSuppliers: [
      {
        id: 'contract-001',
        supplierId: 'supplier-003',
        supplierName: 'Constructora de Occidente S.A.',
        contractCount: 24,
        totalAmount: 142500000,
        currency: 'GTQ',
        riskLevel: 'high',
      },
      {
        id: 'contract-002',
        supplierId: 'supplier-004',
        supplierName: 'Ingeniería Global de Guatemala',
        contractCount: 18,
        totalAmount: 98210000,
        currency: 'GTQ',
        riskLevel: 'low',
      },
      {
        id: 'contract-003',
        supplierId: 'supplier-005',
        supplierName: 'Suministros Técnicos S.A.',
        contractCount: 42,
        totalAmount: 45000000,
        currency: 'GTQ',
        riskLevel: 'medium',
      },
      {
        id: 'contract-004',
        supplierId: 'supplier-006',
        supplierName: 'Distribuidora El Faro',
        contractCount: 11,
        totalAmount: 32150000,
        currency: 'GTQ',
        riskLevel: 'low',
      },
    ],
  },
}

// Suppliers
export const mockSuppliers: Record<string, Supplier> = {
  'supplier-001': {
    id: 'supplier-001',
    name: 'Constructora del Norte, S.A.',
    nit: '837492-5',
    industry: 'Infraestructura',
    totalContracts: 142,
    totalAwarded: 45200000,
    currency: 'Q',
    clientEntities: 12,
    singleBidderPercentage: 64,
    period: '2019-2024',
    yearlyData: [
      { year: 2021, amount: 9500000, contractCount: 53 },
      { year: 2022, amount: 15100000, contractCount: 42 },
      { year: 2023, amount: 8200000, contractCount: 19 },
      { year: 2024, amount: 12400000, contractCount: 28 },
    ],
    alerts: [
      {
        id: 'supplier-alert-001',
        severity: 'critical',
        title: 'Concentración en una Entidad',
        description:
          'El 85% de los contratos del 2024 provienen de la Municipalidad de San José Pinula.',
        date: 'Jun 12, 2024',
      },
      {
        id: 'supplier-alert-002',
        severity: 'medium',
        title: 'Fraccionamiento detectado',
        description:
          'Múltiples adjudicaciones por debajo del umbral de licitación en un mismo mes.',
        date: 'Mayo 28, 2024',
      },
      {
        id: 'supplier-alert-003',
        severity: 'medium',
        title: 'Oferta Única Recurrente',
        description:
          'Ha ganado los últimos 5 concursos sin competidores registrados en el portal.',
        date: 'Abr 15, 2024',
      },
    ],
    associates: [
      {
        id: 'associate-001',
        name: 'Marco Antonio Rivera',
        role: 'Representante Legal',
        participation: '40%',
        otherCompanies: 3,
      },
      {
        id: 'associate-002',
        name: 'Lucía Fernanda López',
        role: 'Socio Fundador',
        participation: '60%',
        otherCompanies: 1,
      },
    ],
  },
}

// Entity List Items (for explorer)
export const mockEntityList: EntityListItem[] = [
  {
    id: 'entity-001',
    name: 'Ministerio de Comunicaciones, Infraestructura y Vivienda',
    shortName: 'MICIVI',
    type: 'ministerio',
    totalContracts: 1482,
    totalAmount: 4200000000,
    currency: 'GTQ',
    activeAlerts: 14,
    riskLevel: 'high',
  },
  {
    id: 'entity-002',
    name: 'Municipalidad de Guatemala',
    shortName: 'MUNIGUATE',
    type: 'municipalidad',
    totalContracts: 2341,
    totalAmount: 1850000000,
    currency: 'GTQ',
    activeAlerts: 8,
    riskLevel: 'medium',
  },
  {
    id: 'entity-003',
    name: 'Ministerio de Salud Pública y Asistencia Social',
    shortName: 'MSPAS',
    type: 'ministerio',
    totalContracts: 3420,
    totalAmount: 5200000000,
    currency: 'GTQ',
    activeAlerts: 22,
    riskLevel: 'high',
  },
  {
    id: 'entity-004',
    name: 'Instituto Guatemalteco de Seguridad Social',
    shortName: 'IGSS',
    type: 'instituto',
    totalContracts: 4521,
    totalAmount: 8900000000,
    currency: 'GTQ',
    activeAlerts: 31,
    riskLevel: 'critical',
  },
  {
    id: 'entity-005',
    name: 'Ministerio de Educación',
    shortName: 'MINEDUC',
    type: 'ministerio',
    totalContracts: 1890,
    totalAmount: 2100000000,
    currency: 'GTQ',
    activeAlerts: 5,
    riskLevel: 'low',
  },
  {
    id: 'entity-006',
    name: 'Municipalidad de Mixco',
    shortName: 'MUNIMIXCO',
    type: 'municipalidad',
    totalContracts: 542,
    totalAmount: 320000000,
    currency: 'GTQ',
    activeAlerts: 12,
    riskLevel: 'high',
  },
  {
    id: 'entity-007',
    name: 'Secretaría General de Planificación',
    shortName: 'SEGEPLAN',
    type: 'secretaria',
    totalContracts: 234,
    totalAmount: 89000000,
    currency: 'GTQ',
    activeAlerts: 2,
    riskLevel: 'low',
  },
  {
    id: 'entity-008',
    name: 'Municipalidad de Villa Nueva',
    shortName: 'MUNIVN',
    type: 'municipalidad',
    totalContracts: 678,
    totalAmount: 450000000,
    currency: 'GTQ',
    activeAlerts: 9,
    riskLevel: 'medium',
  },
]

// Supplier List Items (for explorer)
export const mockSupplierList: SupplierListItem[] = [
  {
    id: 'supplier-001',
    name: 'Constructora del Norte, S.A.',
    nit: '837492-5',
    industry: 'Infraestructura',
    totalContracts: 142,
    totalAwarded: 45200000,
    currency: 'GTQ',
    clientEntities: 12,
    riskLevel: 'critical',
    singleBidderPercentage: 64,
  },
  {
    id: 'supplier-002',
    name: 'Suministros Médicos del Norte, S.A.',
    nit: '8392104-5',
    industry: 'Salud',
    totalContracts: 89,
    totalAwarded: 142500000,
    currency: 'GTQ',
    clientEntities: 5,
    riskLevel: 'high',
    singleBidderPercentage: 72,
  },
  {
    id: 'supplier-003',
    name: 'Constructora de Occidente S.A.',
    nit: '1234567-8',
    industry: 'Infraestructura',
    totalContracts: 234,
    totalAwarded: 312000000,
    currency: 'GTQ',
    clientEntities: 18,
    riskLevel: 'high',
    singleBidderPercentage: 45,
  },
  {
    id: 'supplier-004',
    name: 'Ingeniería Global de Guatemala',
    nit: '9876543-2',
    industry: 'Consultoría',
    totalContracts: 156,
    totalAwarded: 98210000,
    currency: 'GTQ',
    clientEntities: 24,
    riskLevel: 'low',
    singleBidderPercentage: 12,
  },
  {
    id: 'supplier-005',
    name: 'Suministros Técnicos S.A.',
    nit: '5432109-6',
    industry: 'Tecnología',
    totalContracts: 312,
    totalAwarded: 78500000,
    currency: 'GTQ',
    clientEntities: 32,
    riskLevel: 'medium',
    singleBidderPercentage: 28,
  },
  {
    id: 'supplier-006',
    name: 'Distribuidora El Faro',
    nit: '7654321-0',
    industry: 'Distribución',
    totalContracts: 89,
    totalAwarded: 32150000,
    currency: 'GTQ',
    clientEntities: 8,
    riskLevel: 'low',
    singleBidderPercentage: 15,
  },
  {
    id: 'supplier-007',
    name: 'Farmacéutica Central, S.A.',
    nit: '2345678-9',
    industry: 'Salud',
    totalContracts: 456,
    totalAwarded: 520000000,
    currency: 'GTQ',
    clientEntities: 14,
    riskLevel: 'medium',
    singleBidderPercentage: 35,
  },
  {
    id: 'supplier-008',
    name: 'Transportes Unidos del Sur',
    nit: '3456789-0',
    industry: 'Transporte',
    totalContracts: 67,
    totalAwarded: 18900000,
    currency: 'GTQ',
    clientEntities: 6,
    riskLevel: 'low',
    singleBidderPercentage: 8,
  },
]
