import type {
  Alert,
  AlertDetail,
  Supplier,
  SupplierListItem,
} from './types'

// Alerts
export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    entityId: 'entity-001',
    entityName: 'Ministerio de Comunicaciones, Infraestructura y Vivienda',
    riskLevel: 'high',
    signalKey: 'single_bidder',
    signalType: 'Proveedor único recurrente',
    signalIcon: 'person_off',
    year: '2024',
    contractCount: 14,
    totalAmount: 142800000,
    currency: 'GTQ',
  },
  {
    id: 'alert-002',
    entityId: 'entity-002',
    entityName: 'Municipalidad de Guatemala',
    riskLevel: 'medium',
    signalKey: 'failed_tenders',
    signalType: 'Alta tasa de desiertos',
    signalIcon: 'event_busy',
    year: '2024',
    contractCount: 8,
    totalAmount: 24500000,
    currency: 'GTQ',
  },
  {
    id: 'alert-003',
    entityId: 'entity-003',
    entityName: 'Ministerio de Salud Pública y Asistencia Social',
    riskLevel: 'high',
    signalKey: 'short_deadline',
    signalType: 'Plazo imposible',
    signalIcon: 'timer_off',
    year: '2024',
    contractCount: 3,
    totalAmount: 89200000,
    currency: 'GTQ',
  },
  {
    id: 'alert-004',
    entityId: 'entity-004',
    entityName: 'Instituto Guatemalteco de Seguridad Social',
    riskLevel: 'medium',
    signalKey: 'direct_purchase',
    signalType: 'Abuso compra directa',
    signalIcon: 'point_of_sale',
    year: '2024',
    contractCount: 52,
    totalAmount: 312000000,
    currency: 'GTQ',
  },
]

// Alert Details
export const mockAlertDetails: Record<string, AlertDetail> = {
  'alert-004': {
    id: 'alert-004',
    entityId: 'entity-004',
    entityName: 'Instituto Guatemalteco de Seguridad Social',
    description:
      'Anomalía detectada en el proceso de adquisición de suministros médicos para la región metropolitana. Patrones de concentración de mercado identificados.',
    riskScore: 94,
    riskLevel: 'critical',
    signals: [
      {
        id: 'signal-001',
        type: 'single_bidder',
        title: '85% de adjudicaciones con oferente único',
        description: 'Proveedor único recurrente',
        icon: 'person_off',
        metrics: [
          { label: 'vs. Promedio sectorial', value: '+62%' },
          { label: 'Contratos vigentes', value: '12' },
        ],
      },
      {
        id: 'signal-002',
        type: 'direct_purchase',
        title: '87% de adjudicaciones vía Art. 43 o 54',
        description: 'Abuso compra directa',
        icon: 'point_of_sale',
        metrics: [
          { label: 'vs. Histórico entidad', value: '+15%' },
          { label: 'Eventos afectados', value: '4' },
        ],
      },
      {
        id: 'signal-003',
        type: 'short_deadline',
        title: '12 adjudicaciones con plazo menor a 72h',
        description: 'Plazo imposible',
        icon: 'timer_off',
        metrics: [
          { label: 'vs. Plazo legal recomendado', value: '-70%' },
          { label: 'Proceso', value: 'NOG 18239401' },
        ],
      },
    ],
    involvedSupplier: {
      id: 'GT-NIT-83921045',
      name: 'Suministros Médicos del Norte, S.A.',
      nit: '83921045',
      totalAwarded: 14250900,
      year: 2024,
    },
    draftInvestigation: `La auditoría de datos en GuateVigila ha detectado una anomalía crítica en el Instituto Guatemalteco de Seguridad Social (IGSS). Durante el último trimestre, el 85% de las adjudicaciones para equipo quirúrgico han sido asignadas a un único proveedor, superando por un margen del 62% el promedio de concentración de mercado del sector salud. Los documentos analizados revelan ventanas de licitación inusualmente cortas, de apenas 72 horas, lo que sugiere un posible direccionamiento de las bases. Esta práctica coincide con un incremento del 24% en los costos unitarios comparados con el mercado regional, representando un potencial perjuicio económico de millones de quetzales para la seguridad social guatemalteca.`,
    registroMercantilUrl: 'https://eregistros.registromercantil.gob.gt/index.jsp?nit=83921045',
    networkMapUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQnO3mDXmtk2fnkxJBRYiQ58hXEEvkzg1jW7D9nVAoSI0EK4fBdcb18nFsHlHV2e3M1bt4_QejyeuxwskqkNqAzrj8gZ_CnZqS7xKIgQWPcwEXwJURGkU1U3mWX75gfnAOeA05ElzVjhXRORk2i4XAzB9yqQZGzOcHgMQootURUkzvJTfYyucxyRzWg7Ymzmmkg0QkD17Zw_88UwLry-FgcaS_dz8MAbce3aV0Xspi-HyRh5Aj4vWPN2GAPS2eyM6bfqy-gXCUUXY',
  },
}

// Suppliers
export const mockSuppliers: Record<string, Supplier> = {
  'supplier-001': {
    id: 'supplier-001',
    name: 'Constructora del Norte, S.A.',
    nit: '837492-5',
    totalContracts: 142,
    totalAwarded: 45200000,
    currency: 'Q',
    clientEntities: 12,
    singleBidderPercentage: 64,
    period: '2019-2024',
    yearlyData: [
      { year: 2021, amount: 9500000, contractCount: 53 },
      { year: 2022, amount: 15100000, contractCount: 42 },
      { year: 2023, amount: 8200000, contractCount: 19 },
      { year: 2024, amount: 12400000, contractCount: 28 },
    ],
    alerts: [
      {
        id: 'supplier-alert-001',
        severity: 'critical',
        title: 'Concentración en una Entidad',
        description: 'El 85% de los contratos del 2024 provienen de la Municipalidad de San José Pinula.',
        date: 'Jun 12, 2024',
      },
      {
        id: 'supplier-alert-002',
        severity: 'medium',
        title: 'Fraccionamiento detectado',
        description: 'Múltiples adjudicaciones por debajo del umbral de licitación en un mismo mes.',
        date: 'Mayo 28, 2024',
      },
      {
        id: 'supplier-alert-003',
        severity: 'medium',
        title: 'Oferta Única Recurrente',
        description: 'Ha ganado los últimos 5 concursos sin competidores registrados en el portal.',
        date: 'Abr 15, 2024',
      },
    ],
  },
}

// Supplier List Items (for explorer)
export const mockSupplierList: SupplierListItem[] = [
  {
    id: 'supplier-001',
    name: 'Constructora del Norte, S.A.',
    nit: '837492-5',
    totalContracts: 142,
    totalAwarded: 45200000,
    currency: 'GTQ',
    clientEntities: 12,
    riskLevel: 'critical',
    singleBidderPercentage: 64,
  },
  {
    id: 'supplier-002',
    name: 'Suministros Médicos del Norte, S.A.',
    nit: '8392104-5',
    totalContracts: 89,
    totalAwarded: 142500000,
    currency: 'GTQ',
    clientEntities: 5,
    riskLevel: 'high',
    singleBidderPercentage: 72,
  },
  {
    id: 'supplier-003',
    name: 'Constructora de Occidente S.A.',
    nit: '1234567-8',
    totalContracts: 234,
    totalAwarded: 312000000,
    currency: 'GTQ',
    clientEntities: 18,
    riskLevel: 'high',
    singleBidderPercentage: 45,
  },
  {
    id: 'supplier-004',
    name: 'Ingeniería Global de Guatemala',
    nit: '9876543-2',
    totalContracts: 156,
    totalAwarded: 98210000,
    currency: 'GTQ',
    clientEntities: 24,
    riskLevel: 'low',
    singleBidderPercentage: 12,
  },
  {
    id: 'supplier-005',
    name: 'Suministros Técnicos S.A.',
    nit: '5432109-6',
    totalContracts: 312,
    totalAwarded: 78500000,
    currency: 'GTQ',
    clientEntities: 32,
    riskLevel: 'medium',
    singleBidderPercentage: 28,
  },
  {
    id: 'supplier-006',
    name: 'Distribuidora El Faro',
    nit: '7654321-0',
    totalContracts: 89,
    totalAwarded: 32150000,
    currency: 'GTQ',
    clientEntities: 8,
    riskLevel: 'low',
    singleBidderPercentage: 15,
  },
]
